devfile/developer-images

universal/ubi8/Dockerfile
Related to https://github.com/eclipse/che/issues/20645
=> Add pylint in ubi8 universal developer image

CONTRIBUTING.md, README.md, base/ubi8/entrypoint.sh, universal/ubi8/Dockerfile
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>
Fixes build of universal image on linux
- try to build the universal image on linux systems
```
$ cd universal/ubi8
$ DOCKER_BUILDKIT=1 docker image build --progress=plain -t quay.io/devfile/universal-developer-image:ubi8-latest .
```
=> chore(build): fix docker build on linux

universal/ubi8/Dockerfile
https://github.com/eclipse/che/issues/19341
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
=> Add shellcheck v0.8.0 dependency.

README.md, universal/ubi8/Dockerfile
Installs PHP 7.4 with libraries, php composer and xdebug from PHP Extension Community Library
=> chore: Install PHP 7.4 with libraries, composer and xdebug

README.md, universal/ubi8/Dockerfile
Fixes https://github.com/eclipse/che/issues/20794
=> feat: add camel-k binary

universal/ubi8/Dockerfile
revert rust changes from my previous PR about camel-k
=> revert rust changes

README.md, universal/ubi8/Dockerfile
Install OpenShift CLI (oc) v4.6
=> feat: add oc binary

README.md, universal/ubi8/Dockerfile
fixes: eclipse/che#21465
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Add JBang to Universal Image

base/ubi8/Dockerfile
Signed-off-by: sdawley <sdawley@redhat.com>
=> Add /ubi to fix update-base-images

.github/workflows/ubi9-build.yaml, base/ubi9/Dockerfile, base/ubi9/entrypoint.sh
A few notes:
* for now I've removed the epel repository, and the couple of packages we were pulling from there. They don't appear to be critical path, but we'll see.
*  the two packages missing are p7zip and p7zip-plugins
=> Add a ubi9 version of Developer Base Image

universal/ubi8/Dockerfile
- Adds git completion
- Adds oc completion
- Define `KUBECONFIG` env var
=> feat: Add git and oc completions

base/ubi8/Dockerfile, base/ubi9/Dockerfile
Just like `rg` makes `grep` less painful, `fd` makes `find` less painful.
=> Add fd to base images

base/ubi8/Dockerfile, base/ubi9/Dockerfile
I thought it would be useful to have manual pages included for the tools that come from GitHub. So here they are!
=> Install man pages for base image utils from github

universal/ubi8/Dockerfile
Update kubedock to latest version that includes some [important fixes](https://github.com/joyrex2001/kubedock/issues/34#issuecomment-1708931704).
=> Update kubedock to version 0.13.0

universal/ubi8/Dockerfile
Add Skaffold to UDI.
resolves https://github.com/eclipse/che/issues/22483
=> feat: add skaffold

universal/ubi8/Dockerfile
chore: feat: updated to node 18 because 16 is EOL
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
https://issues.redhat.com/browse/CRW-4855 - working on a devfile for chectl and realized that it requires Node 18 but UDI image still only has 16 in it. :( 
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
Reviewers, please comment how you tested the PR when approving it.
=> chore: feat: updated to node 18 because 16 is EOL

universal/ubi8/Dockerfile
https://github.com/eclipse/che/issues/22374
=> chore: Remove docker since it is not supported

universal/ubi8/Dockerfile
https://github.com/eclipse/che/issues/22374
=> chore: Add alias docker=podman

README.md, universal/ubi8/Dockerfile
Add OpenShift Pipelines CLI (tkn)
Related issue: https://issues.redhat.com/browse/CRW-3570
=> feat: add OpenShift Pipeline CLI (tkn)

.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi8.yaml, .github/workflows/ubi8-build.yaml, .github/workflows/ubi9-build.yaml
add missing clean-up stage to one of the jobs
and some formatting for all of these stages.
=> fix: more fixes for cleaning up space stage

universal/ubi8/Dockerfile
see download page for updated URL: https://github.com/apache/camel-k/releases
=> Update kamel CLI from 1.11 to 2.2

.github/CODEOWNERS
Update the list of code owners by removing Andrew and adding David
=> Add David as a code owner
