devfile/developer-images

base/ubi8/Dockerfile
Currently if you clone https://github.com/Apress/repo-with-large-file-storage it won't clone LFS files you'll see files with few bytes
And if you try with the updated image, files are there as expected
example of repository to clone: https://github.com/Apress/repo-with-large-file-storage
https://github.com/eclipse/che/issues/20642
=> feat: add git-lfs support

README.md, universal/ubi8/Dockerfile
- Install `gdb`, `clangd` and `clang` with libraries
- Remove `git` from universal image since it was installed in base image
=> chore: install clang toolset and gdb

README.md, universal/ubi8/Dockerfile
=> chore: install dotnet 5.0

universal/ubi8/Dockerfile
Making the lombok.jar available in UDI. 
It is needed for Java+Lombok devfile
=> chore: add Lombok.jar into the UDI

README.md, universal/ubi8/Dockerfile
Added rustup and used it to install rust developement tool set.
Part of https://github.com/eclipse/che/issues/20850.
Tested with the [helloworld-rust Che sample](https://github.com/che-samples/helloworld-rust).
=> Add rust tooling, language server included

README.md, universal/ubi8/Dockerfile
default is still Java11
Fixes https://github.com/eclipse/che/issues/20793
=> feat: Add Java8 and Java17

.github/workflows/ubi8-build.yaml
The current base image published on Quay.io is identical to the universal image.
That happens because the image built from `universal/ubi8/Dockerfile` is tagged and published as both `quay.io/devfile/base-developer-image` and `quay.io/devfile/universal-developer-image`.
This PR separate the 2 builds in 2 distinct jobs.
Fixes https://github.com/eclipse/che/issues/20798
=> Fix GH action publishing the wrong base image

universal/ubi8/Dockerfile
Add necessary libraries for Java AWT. This changes proposal adds an ability to use UDI with JetBrains-based IDEs in the Eclipse Che.
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
=> feat: add necessary libraries for Java AWT

README.md, universal/ubi8/Dockerfile
This changes proposal adds `yq` library that installs via `pip` to allow to parse yaml files from the command line. Like it done with JSON files with `jq`.
Part of https://github.com/eclipse/che/issues/21003
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
=> feat: add yq library to operate with yaml files from the command line

universal/ubi8/Dockerfile
It provides NodeJS 12, NodeJS 14 and 16
16/LTS is the default
=> feat: use nvm to install node and also provides different nodejs versions

README.md, universal/ubi8/Dockerfile
Since `e2fsprogs-static` package has removed from RHEL 8 distribution, it is not possible to install from the repository.
See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#removed-packages_changes-to-packages
There is a proposal to include latest released version of `e2fsprogs`.
`e2p.so` is used by the IntelliJ IDEA [FileSystemUtil.java#L763-L769](https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/openapi/util/io/FileSystemUtil.java#L763-L769).
Part of https://github.com/eclipse/che/issues/21007
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
=> feat: add e2fsprogs library for support IntelliJ IDEA 2021

README.md, universal/ubi8/Dockerfile
Install [mandrel](https://github.com/graalvm/mandrel) (downstream distribution of the GraalVM community edition)
Size of installed Mandrel is 408M 
Related issue: https://github.com/eclipse/che/issues/21145
=> chore: add mandrel (downstream distribution of the GraalVM)

README.md, universal/ubi8/Dockerfile
Please note that AdoptOpenJDK has been migrated to Eclipse Adoptium
which is producing Temurin build. See
https://api.adoptopenjdk.net/migration.html or
https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/
fixes eclipse/che#21475
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Update Java to version more recent than security release of April 2022

.devfile.yaml, universal/ubi8/Dockerfile
With this change it's possible to use the UDI image [to run buildah on rootless mode on OpenShift](https://github.com/containers/buildah/blob/main/docs/tutorials/05-openshift-rootless-build.md)
It's related to [this issue](https://github.com/eclipse/che/issues/19305).
=> Update UDI to make it possible to build container with buildah in rootless mode

README.md
For some reason trailing `/` is not redirecting correctly on the quay.io e.g. valid link https://quay.io/repository/devfile/universal-developer-image vs invalid https://quay.io/repository/devfile/universal-developer-image/ (results in `Repository not found`)
=> fix: Updating links to the quay.io

base/ubi8/Dockerfile, universal/ubi8/Dockerfile
Issue: che-incubator/chectl#2239
The chectl package-binaries command uses shasum, so we either have to add shasum to the image used to create a workspace or add a symlink from sha256sum (which we do have).
Steps to reproduce: 
- Create a Chectl workspace in the che dogfooding instance from https://github.com/SDawley/chectl/tree/contribute (my branch that contains the build fixes).
- Build Chectl
- Run the package-binaries command
- command fails with `/bin/sh: shasum: command not found`
Steps to verify:
- Create a Chectl workspace in the che dogfooding instance from https://github.com/SDawley/chectl/tree/contribute. It uses the latest ubi image by default.
- Build Chectl
- Run the package-binaries command
=> Feat: Small change to add shasum for chectl

README.md, base/ubi8/Dockerfile
Fix to previous PR. I noticed the image build failed because shasum is a perl script and not actually equivalent to sha1sum.
Issue: che-incubator/chectl#2239
The chectl package-binaries command uses shasum, so we either have to add shasum to the image used to create a workspace or add a symlink from sha256sum (which we do have).
Steps to reproduce: 
- Create a Chectl workspace in the che dogfooding instance from https://github.com/SDawley/chectl/tree/contribute (my branch that contains the build fixes).
- Build Chectl
- Run the package-binaries command
- command fails with `/bin/sh: shasum: command not found`
Steps to verify:
- Create a Chectl workspace in the che dogfooding instance from https://github.com/SDawley/chectl/tree/contribute. It uses the latest ubi image by default.
- Build …
=> Fix: actual install command is perl-Digest-SHA

README.md, base/ubi8/Dockerfile
Fix to previous PR. I noticed the image build failed because shasum is a perl script and not actually equivalent to sha1sum.
Issue: https://github.com/che-incubator/chectl/pull/2239
The chectl package-binaries command also packages for windows and needs 7zip to do so.
I also noticed that the sizes in the readme were slightly out of date so I updated the compressed size to match the size in quay and the uncompressed size to how big they were when running locally.
Steps to reproduce:
- Create a Chectl workspace in the che dogfooding instance from https://github.com/SDawley/chectl/tree/contribute (my branch that contains the build fixes).
- Build Chectl
- Run the package-binaries command
command fails:
`oclif-dev: building target chectl-win32-x64.tar.gz
/bin/sh: 7z: command not found
› …
=> fix: add p7zip-plugins to base image for chectl

base/ubi8/Dockerfile
Fix to previous PR. 
Issue: https://github.com/che-incubator/chectl/pull/2239
epel needs to be added so that 7zip can be found and installed
Steps to reproduce:
https://github.com/devfile/developer-images/actions/runs/3274136656/jobs/5387344563
`#9 3.828 No match for argument: p7zip-plugins
#9 3.834 Error: Unable to find a match: p7zip-plugins`
Steps to verify:
- Build the dockerfile successfully
=> Fix: add epel repo so p7zip can be found.

.github/workflows/ubi8-build.yaml, base/ubi8/Dockerfile, universal/ubi8/Dockerfile
Changes for https://github.com/eclipse/che/issues/21575
Set the dockerfiles to use a specific tag and added the commented html line which should allow the update-base-images action to keep them up to date.
=> Add comments so dockerfiles can be updated by update-base-images

.github/workflows/ubi8-build.yaml, base/ubi8/Dockerfile, universal/ubi8/Dockerfile
chore: dockerfile update
since ubi8 images now include go1.18 rpms, we need to update the go get command to go install;
also dedupe the rpm cleanup commands and set an older tag so we can verify new GHA works with https://github.com/eclipse/che/issues/21575
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
Last good build: https://github.com/devfile/developer-images/actions/runs/3410216777/jobs/5672905276 (used golang 1.17 with `go get`)
Last build: https://github.com/devfile/developer-images/actions/runs/3643285736/jobs/6165373421 (used golang 1.18; failed due to error `'go get' is no longer supported outside a module.`)
1. merge it and watch https://github.com/devfile/developer-images/actions/workflows/ubi8-build.yaml
2. then check quay for new images at:
* …
=> chore: update UDI dockerfile to go1.18

README.md
Add `git-lfs` to `README.md` as it's included in the base-developer-image
https://github.com/devfile/developer-images/blob/13008afdefb64f16c906c6d8b2aeb58deae8f8c2/base/ubi8/Dockerfile#L23
=> Add `git-lfs` to `README.md`

.github/workflows/ubi9-build.yaml
Added `platforms: linux/amd64` in ubi9 build.
=> Build linux/arm64 ubi9 base image in GH action

universal/ubi8/Dockerfile
Setting `sdkman_auto_env` so that [`.sdkmanrc` is automatically used](https://sdkman.io/usage#env).
For testing I have build and push the image `quay.io/mloriedo/universal-developer-image:ubi8-latest` and used this [devfile](https://github.com/l0rd/inventory-quarkus/blob/sdkman_auto_env/.devfile.yaml#L111).
=> Set sdkman_auto_env: true

README.md, universal/ubi8/Dockerfile
Update dotnet version to 6.0
Related issues: https://github.com/eclipse/che/issues/22077, https://github.com/eclipse/che/issues/21978
=> chore: update dotnet version to 6.0

.github/workflows/empty-worksapce-smoke-test-on-minikube.yaml, .github/workflows/ubi8-build.yaml
* This PR adds a check-up on each opened PR that makes the next steps:
1) reusing Job which builds UDI-8 image and builds a new image
2) after success building the just created tag pass to the Empty workspace test workflow
3) Empty workspace test workflow run the minikube set the DWO + cert-manager and pre-pull image which was created in the previous workflow
4) After this run test which creates an Empty workspace on the image and tests basic functionality (check that workspace is leave, clone repo into container)
=> Add action for testing UDI images

universal/ubi8/Dockerfile, universal/ubi8/entrypoint.sh, universal/ubi8/podman-wrapper.sh
This PR partially addresses https://github.com/eclipse/che/issues/20227. 
The approach of this PR is to add [`kubedock`](https://github.com/joyrex2001/kubedock/) in the universal developer image (Eclipse Che default image) and start it automatically if the env variable `KUBEDOCK_ENABLED` is set to `true` (can be set using a devfile).
When `KUBEDOCK_ENABLED=true` then the following commands will be executed with kubedock (the remaining commands, in particular `podman build`, will be executed by the local podman):
```
podman run
podman ps
podman exec
podman cp
podman logs
podman inspect
podman kill
podman rm
podman wait
podman stop
podman start
```
The `kubedock` approach allows to run containers from a container running on Kubernetes but has a few limits:
- `podman build -t <image> . && …
=> feat: add support to run kubedock at workspace startup

.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi8.yaml
* According to the issue: https://github.com/eclipse/che/issues/22364 seems there is one way to avoid the problem:
- Build image directly in the minikube using connection docker daemon 
- Change pull policy for DWO and run a test
=> Revork GitHub workflow without using secrets

base/ubi8/Dockerfile, universal/ubi8/Dockerfile
Update the universal developer image Dockerfile to run
```bash
chgrp -R 0 /home/user && chmod -R g=u /home/user
```
after every RUN step that impacts `/home/user` significantly. This has the effect of reducing the udi8 image's size from `9.34GB` to `6.59GB` (on disk) -- a ~30% decrease.
Previously, one of the last steps in the build process was
```
RUN mkdir -p /home/user && chgrp -R 0 /home && chmod -R g=u /etc/passwd /etc/group /home
```
executing `chgrp` and `chmod` on `/home` resulted in a new layer in the image with _all_ of the files in `/home` copied (due to the overlay filesystem). By setting permissions as we create files (i.e. in the same RUN command that creates them) we avoid this last step exploding image size:
* Before
```
❯ docker history …
```
=> chore: Update how file permissions in /home/user are handled

universal/ubi8/Dockerfile, universal/ubi8/entrypoint.sh
`/home/user/.local/bin` directory may contain binaries, that could be inaccessible when using VS Code tasks. 
For instance, this directory contains a link to `podman`. If I launch VS Code task, environment variables appear to be not properly/completely initialized and `/home/user/.local/bin` is not added to `PATH`.
One of the solutions is to create a directory for binaries and add it to the `PATH` variable in the Dockerfile directly.
Required for https://github.com/eclipse/che/issues/22292
=> chore: define user directory for binaries

.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi8.yaml
* According to the issue: https://github.com/eclipse/che/issues/22509, we have instability runs on the latest verifications
* The root cause of the failures -  is limited Disk space in the provided GitHub Free plan - just 14 GB of disk space. We need to save disk space as much as possible. The main idea of this PR is to remove built-in images on the VM provided by the GitHub side. Potentially it can free about 1.5 GB. 
* Also, after building and using the universal base image, we may remove it. It can free about 450 MB. I hope this will help.
=> Add parts to save disk space into Github workflow for increasing stability

base/ubi8/.stow-local-ignore, base/ubi8/Dockerfile, base/ubi8/entrypoint.sh, universal/ubi8/Dockerfile, universal/ubi8/entrypoint.sh
This PR aims to resolve https://github.com/eclipse/che/issues/22412, where enabling `devEnvironments.persistUserHome` in the Che Cluster CR will cause the workspace's PVC to mount to `/home/user/`, overwriting any tools, configurations, etc. that are present in the UDI's  `/home/user/` directory.
In order to resolve this issue, we are now installing tools (and most config files) to `/home/tooling/` and using GNU stow to create symbolic links to `/home/user/` for all files in `/home/tooling/` (with the exception of `.viminfo`, which cannot be a symbolic link by vim's design). 
Rather than trying to keep `$PATH` to be exactly the same as prior to this change (i.e. tooling binaries are found in `/home/user/`) , `$PATH` has been modified to contain the appropriate directories in …
=> Move tools & configs from /home/user/ to /home/tooling/

universal/ubi8/Dockerfile, universal/ubi8/containers.conf
Creates `/etc/containers/containers.conf` configuration file to increase amount of opened files for `podman build / podman run`
Required for https://github.com/eclipse/che/issues/22292
=> fix: Increase amount of opened files

universal/ubi8/Dockerfile
This PR aims to fix eclipse/che#22029, with the scope limited to pre-creating config directories for the following common tools:
- Maven: `/home/user/.m2/`
- Gradle: `/home/user/.gradle/`
- Pip: `/home/user/.config/pip/`
- Cargo: `/home/user/.cargo/`
- Sbt: `/home/user/.sbt/1.0/`
- PHP: `/home/user/.composer/`
- .NET: `/home/user/.nuget`
As well as a `/home/user/certs/` directory.
Yarn & npm were excluded since they are supposed to be placed in the $HOME directory (`~/.yarnrc` ,` ~.npmrc`)
There might be other tools which support configuration files that I've missed in this PR, please feel free to suggest any.
I've pushed `quay.io/aobuchow/universal-developer-image:m2` for testing this PR, I also used the following [devfile](https://github.com/AObuchow/java-devfile-test/blob/main/devfile.y …
=> Pre-create common config directories

README.md, universal/ubi8/Dockerfile
Updates python from 3.9 to 3.11
**Related issue:** https://issues.redhat.com/browse/CRW-4944
**To test:**
- Check that python 3.11 is installed in the image
or
- Run a python workspace using [![Contribute](https://www.eclipse.org/che/contribute.svg)](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/#/https://github.com/svor/python-hello-world/tree/che-python311)
=> chore:update python to 3.11.x

.clomonitor.yaml
All of the devfile repositories are currently being monitored on https://clomonitor.io/projects/cncf/devfile. As there are no releases planned for GitHub and the monitor is only tracking GitHub releases I am marking this as exempt on the monitor. The addition of the `.clomonitor.yaml` file allows this exemption to be properly tracked. Additionally it allows users who view the `developer-images` repo on the monitor to know that releases are going to `quay.io`.
fixes https://github.com/devfile/api/issues/1388
=> add clo monitor exemption for release

universal/ubi8/Dockerfile
This PR sets write permissions for `/etc/pki` directory.
It allows to run `update-ca-trust` command to import mounted certificates from `/etc/pki/ca-trust/source/anchors` directory.
1. Run the command and observe the error:
```bash
$ docker run -ti quay.io/devfile/universal-developer-image:ubi8-latest  -- update-ca-trust
Kubedock is disabled. It can be enabled with the env variable "KUBEDOCK_ENABLED=true"
set in the workspace Devfile or in a Kubernetes ConfigMap in the developer namespace.
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt: Unknown error 13
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: Unknown error 13
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem: Unknown error 13 …
```
=> chore: Configure permissions for `/etc/pki` directory

universal/ubi8/Dockerfile
Use new [Kubernetes community repository](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/), because the old one is no longer available (And udi developer image cannot be built).
New repositories has k8s version in its path, so we'd need to manually update this dockerfile (`K8S_VERSION` env var) if we want to switch to newer k8s packages version.
This issue was raised in Che project https://github.com/eclipse/che/issues/22868
=> fix: use new yum repository for kubectl

.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi8.yaml, .github/workflows/ubi8-build.yaml, .github/workflows/ubi9-build.yaml
GH Actions run into space limits, so remove unneeded modules from ubuntu runner, like android
related issue https://github.com/eclipse/che/issues/22876
=> fix: remove android modules from ubuntu runner to free space

universal/ubi8/Dockerfile
after 4.6, mirror has changed of place as indicated on https://mirror.openshift.com/pub/openshift-v4/clients/oc/%24__DEPRECATED_LOCATION__PLEASE_READ__.txt
`Please direct x86_64 users and automation to the new oc client locations under: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/`
=> Update oc to 4.15

universal/ubi8/Dockerfile
```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/home/user/.cache/yarn/v6/npm-string-width-cjs-4.2.3-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
error next@14.1.3: The engine "node" is incompatible with this module. Expected version ">=18.17.0". Got "18.16.1"
error Found incompatible module.
info Visit …
```
=> chore: update Node.js version to 18.19.1

base/ubi8/Dockerfile, base/ubi9/Dockerfile, universal/ubi8/Dockerfile
When we're extracting tar archives, always use --no-same-owner, so that ownership doesn't get set to oddball values that might have been used by the creator of those tar archives.
I'm running podman as an unprivileged user, and the default configuration can't build or pull images with content ownership UIDs or GIDs above 65536 or so.  Examples that I ran into in quay.io/devfile/universal-developer-image@sha256:2364d29270cdeadb15042785411900776a0b57dadc352befcff547242dfd8eb1 include /usr/local/bin/LICENSE (301071:301071) and /usr/local/bin/tkn (in two layers, one owned by 301071:64025, the other by 0:1000640000).
With this change applied, I can pull the built image without triggering an error.
=> Dockerfiles: run tar x with --no-same-owner

base/ubi8/Dockerfile
Stow recently released version 2.4.0, which [does not allow](https://github.com/eclipse-che/che/issues/22957#issue-2285143021) stowing absolute symbolic links. As a temporary workaround, this PR downgrades stow back to version 2.3.1.
Stow is being downloaded from a GNU mirror, and then verified using the official GNU keyring (see the bottom of https://ftp.gnu.org/README). We remove the GNU gpg related files once we're done with them.
Unfortunately, the binary of stow is not available for direct usage, so stow is built and then moved to `/usr/bin/` so that it is available on $PATH to be used for the rest of the UBI & UDI builds (moving stow to `/usr/local/bin/` didn't seem to put it on $PATH).
Fixes https://github.com/eclipse-che/che/issues/22957
=> Fix: pin stow to version 2.3.1

README.md, universal/ubi8/Dockerfile
Update dotnet version from 6.0 to 8.0, latest LTS version at this time.
Signed-off-by: Alex Popescu <pop.alx@gmail.com>
=> Update dotnet  from 6.0 to 8.0

base/ubi8/Dockerfile, base/ubi8/kubedock_setup.sh, base/ubi8/podman-wrapper.sh
This PR fixes the issue where podman was not found when there is a volume mounted to /home/user/.local.
Fixes https://github.com/eclipse-che/che/issues/23095
In the base image, before this PR an empty `/home/tooling/.local` directory is created. Stowing this empty directory to `/home/user` created a hard link for the /home/.local directory, which caused both `/home/user/.local` and `/home/tooling/.local` to be affected by the volume mount to `/home/user/.local`.
This PR removes the `/home/tooling/.local` directory, since it was not used at all in the Dockerfile, and was only used in the entrypoint to store the podman wrapper. In this PR, the podman wrapper set up by the entrypoint is now stored in `/home/user/.local` instead.
1. Build the base image:
```
$ cd base/ubi8
$ DOCKER_BUILDKIT=1 …
```
=> Remove unused /home/tooling/.local

universal/ubi8/Dockerfile
Upgrade Node 20 from 20.7.0 to 20.18.0
it's need for [devworkspace-generator](https://github.com/devfile/devworkspace-generator) development
=> chore:bump version of node 20

.github/workflows/empty-worksapce-smoke-test-on-minikube-ubi8.yaml, .github/workflows/empty-worksapce-smoke-test-on-minikube-ubi9.yaml, README.md, base/ubi9/.stow-local-ignore, base/ubi9/Dockerfile, base/ubi9/entrypoint.sh, base/ubi9/kubedock_setup.sh, base/ubi9/podman-wrapper.sh, universal/ubi9/Dockerfile, universal/ubi9/containers.conf, universal/ubi9/entrypoint.sh
Part of https://github.com/eclipse-che/che/issues/23034
To test:
1. Set env vars:
```
BASE_IMAGE=quay.io/<username>/<repo>:ubi9
UDI=quay.io/<username/<repo>:udi
```
2. Build and push the base image
```
cd base/ubi9
DOCKER_BUILDKIT=1 docker image build --progress=plain -t $BASE_IMAGE .
docker push $BASE_IMAGE
```
3. Build and push the udi image  
First, replace line 4 of the udi dockerfile [here](https://github.com/dkwon17/developer-images/blob/b4140ecc24b8144f3a858a6be39f25202d362e84/universal/ubi9/Dockerfile#L4) so that the base image matches the base image built from step 2.
Then, run the following:
```
cd universal/ubi9
DOCKER_BUILDKIT=1 docker image build --progress=plain -t $UDI .
docker push $UDI
```
I've built and pushed my own images for testing here:
``` …
```
=> Update ubi9 and add ubi9-based developer image

.devfile.yaml
can build the base, but not the universal on Developer Sandbox:
=> chore: bumping memoryLimit in devfile

base/ubi9/Dockerfile, base/ubi9/entrypoint.sh
Add logic to `entrypoint.sh` to detect support for `fuse-overlayfs`
=> Detect support for fuse-overlayfs

README.md, universal/ubi9/Dockerfile
Gopls v0.17.0 was released recently on Dec 11, which breaks the UDI build with this error:
```
#20 6.448 go: golang.org/x/tools/gopls@latest: golang.org/x/tools/gopls@v0.17.0 requires go >= 1.23.1 (running go 1.22.7; GOTOOLCHAIN=local)
```
This PR updates the dockerfile to use gopls v0.16.2 which is compatible with go version 1.22.7.
To test this PR, run:
```
cd universal/ubi9 && DOCKER_BUILDKIT=1 docker image build --progress=plain -t quay.io/devfile/universal-developer-image:ubi9-latest .
```
and verify that the build succeeds.
=> Keep gopls version to golang.org/x/tools/gopls v0.16.2

base/ubi9/Dockerfile
This should fix several critical and high vulenrabilities.
CRITICAL:
GHSA-v23v-6jw2-98fq
GHSA-v778-237x-gjrc
HIGH:
CVE-2024-34156
CVE-2024-34158
GHSA-w32m-9786-jp63
=> fix: Upgrade kubedock

base/ubi9/.copy-files, base/ubi9/entrypoint.sh
Files under `/home/tooling/.config` are not stowed in the entrypoint because it is in the `.stow-local-ignore` file. Stow ignores everything in the `.config` folder because the `/home/user/.config` folder should be created in the entrypoint in order to have proper user permissions required for Podman 5.x.
This PR fixes https://issues.redhat.com/browse/CRW-8932
See https://github.com/devfile/developer-images/pull/197
How I tested this PR:
1. Build the base image. My base image is: `quay.io/dkwon17/base-developer-image:persist-config-files`.
```
cd base/ubi9 && podman image build -t  {base image} .
```
2. Create the following files somewhere in your filesystem:
<details><summary>Dockerfile</summary>
```
FROM {base image}
COPY test.conf /home/tooling/.config/test/test-nested.conf
COPY …
```
=> fix: create links in entrypoint for files under /home/tooling/.config

base/ubi9/.stow-local-ignore, base/ubi9/Dockerfile, base/ubi9/entrypoint.sh
For https://issues.redhat.com/browse/CRW-8932 and https://issues.redhat.com/browse/CRW-8598.
To test this PR:
Build the base image:
```
$ cd base/ubi9 && DOCKER_BUILDKIT=1 docker image build --progress=plain -t <BASE_IMAGE> .
```
Create these 4 empty files:
```
.
└── some-directory/
├── config
├── config2
├── case1.Dockerfile
└── case2.Dockerfile
```
<details><summary>Case 1: Testing CRW-8932</summary>
Put the following into `case1.Dockerfile`:
```
FROM <BASE_IMAGE>
RUN mkdir -p /home/tooling/.config/test
COPY config2 /home/tooling/.config/test/
COPY config /home/tooling/.config/
USER root
RUN chmod 777 /home/tooling/.config/test/config2 /home/tooling/.config/config
USER 1001
```
Build the image:
```
docker build -t quay.io/<your_username>/base-developer-image:case1 -f case1.Dockerfile . …
```
=> Update .config symlink logic and add .copy-files logic
